web_search:
  description: "Search the web for specified query"
  agent: search_agent
  expected_output: "Raw search results"

empathising:
  description: >
    Analyze the user's emotional tone and language cues and give empathetic responses to help
    the user feel validated.
  expected_output: >
    A short paragraph followed by a question about {topic}. Tone of response should be adjusted
    to match the user's emotional state to provide comfort and understanding.
  agent: empathiser

providing_insight:
  description: >
    Identify recurring themes in the users thought process and conversations, also summarise
    key themes from previous conversations to help the user get a clear understanding of their own
    thought process 
  expected_output: >
    List of 3 bullet points that are atleast 1 sentence long along with a question at the end for self
    reflection about {topic}.
  agent: insight_agent

mindfulness_techniques:
  description: >
    Provide short guided mindfullness prompts to help the user stay grounded even in a negative headspace. 
  expected_output: >
    A few sentences followed by few bullet points about different techniques used to stay grounded with reference to {topic}.
    Addtionally, adjust response appropriately if user uses any high stress language of sort.
  agent: mindfulness_agent